# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build Go Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev gcc ca-certificates

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Display the release tag
      run: echo ${{ github.event.release.tag_name }}
      
    - name: Build Go Binaries
      run: ./go-executable-build.sh ${{ github.event.release.tag_name }}

    - name: List the executables
      run: ls -l ./release

    - name: Upload to release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./release/multiport-listener-*
        file_glob: true
